# this is overpass.conf file;;;
# see "README.planet-update.md" in the "guide/" directory.

# variables for "op_update_db.sh" script:
# follow recommendation in "README.setup.md"
FLUSH_SIZE=4

# varaibles for "mk_regional_osc.sh" script:

# set to your region poly file name ONLY, place file in your region directory

polyFileName=arizona.poly

# set to your area or region name; used in generated state.txt files
# use short name!

regionName=Arizona

# this is the directory where "getdiff" downloads planet change files
# which depends on its '--source / -s' option or 'SOURCE' key value:

# for daily files: SOURCE = https://planet.osm.org/replication/day
# planetDir=/var/lib/overpass/planet/day

# for hourly files: SOURCE = https://planet.osm.org/replication/hour
# planetDir=/var/lib/overpass/getdiff/planet/hour

# scripts may need adjusments for minute updates.

planetDir=/var/lib/overpass/getdiff/planet/day
